-- =========================================================================
-- FILE: sql/13-Hardening-Gerarchia-Servizi-v1.0.sql
-- TARGET ARCHITETTURALE: ER V4.0 - SUPPLY CHAIN MULTILIVELLO
-- DESCRIZIONE: Introduzione dei codici stabili dei servizi e hardening
--              della gerarchia servizio-sottoservizio con validità
--              temporale, storicizzazione e controllo dei cicli
-- TIPO SCRIPT: Produttivo - modifica struttura, vincoli, indici e trigger
-- =========================================================================

/*
    OBIETTIVI

    1. Introdurre un codice applicativo stabile per ciascun servizio.

    2. Trasformare servizio_componente in una relazione storicizzabile,
       mantenendo più periodi successivi della stessa relazione.

    3. Consentire:
       - più sottoservizi per un servizio principale;
       - più servizi principali per uno stesso sottoservizio;
       - un eventuale servizio padre primario;
       - relazioni multilivello.

    4. Impedire:
       - un servizio collegato a sé stesso;
       - duplicati attivi padre-figlio;
       - più padri primari attivi per lo stesso sottoservizio;
       - cicli come A -> B -> C -> A;
       - cancellazioni a cascata della gerarchia.

    5. Ottimizzare:
       - navigazione padre -> sottoservizi;
       - navigazione sottoservizio -> servizi principali;
       - ordinamento dei componenti nella futura interfaccia grafica.

    PRECONDIZIONE

    La tabella public.servizio_componente deve essere vuota.
    La condizione è stata verificata prima della migrazione.

    NOTA SUL CICLO DI VITA

    L'archiviazione generale dei servizi sarà implementata in una
    migrazione dedicata, utilizzando correttamente stato_servizio_id,
    senza introdurre un attributo booleano ridondante in servizio.
*/

BEGIN;

-- =========================================================================
-- 1. VERIFICA DELLA PRECONDIZIONE
-- =========================================================================

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.servizio_componente
    ) THEN
        RAISE EXCEPTION
            'La tabella servizio_componente contiene dati. Migrazione 13 annullata.';
    END IF;
END
$$;

-- =========================================================================
-- 2. CODICE APPLICATIVO STABILE DEI SERVIZI
-- =========================================================================

/*
    Il codice applicativo sarà utilizzato da:

    - interfaccia grafica;
    - API;
    - importazione XLS;
    - esportazione XLS;
    - identificazione delle relazioni tra ambienti differenti.

    Non vengono utilizzati gli ID numerici perché possono cambiare
    tra database di sviluppo, test e produzione.
*/

ALTER TABLE public.servizio
    ADD COLUMN codice_servizio varchar(80);

UPDATE public.servizio
SET codice_servizio =
    CASE nome
        WHEN 'Pronto Soccorso Real-Time'
            THEN 'SRV-PRONTO-SOCCORSO'

        WHEN 'Gestione Identità (Active Directory)'
            THEN 'SRV-IAM-ACTIVE-DIRECTORY'

        WHEN 'Rete e Connettività Perimetrale'
            THEN 'SRV-RETE-PERIMETRALE'

        WHEN 'Database Cartelle Cliniche (EMR)'
            THEN 'SRV-EMR-DATABASE'

        ELSE
            'SRV-LEGACY-' || lpad(id::text, 4, '0')
    END;

ALTER TABLE public.servizio
    ALTER COLUMN codice_servizio SET NOT NULL;

ALTER TABLE public.servizio
    ADD CONSTRAINT servizio_codice_servizio_key
    UNIQUE (codice_servizio);

ALTER TABLE public.servizio
    ADD CONSTRAINT check_codice_servizio_formato
    CHECK (
        codice_servizio ~ '^[A-Z0-9][A-Z0-9_-]{2,79}$'
    );

COMMENT ON COLUMN public.servizio.codice_servizio IS
    'Codice stabile utilizzato da GUI, API e import/export XLS.';

-- =========================================================================
-- 3. INTRODUZIONE DELLA CHIAVE TECNICA DELLA RELAZIONE
-- =========================================================================

/*
    La chiave primaria composta precedente:

        servizio_padre_id, servizio_figlio_id

    non consentiva di conservare più periodi storici della stessa
    relazione.

    Viene quindi introdotto un identificativo tecnico autonomo.
*/

ALTER TABLE public.servizio_componente
    ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.servizio_componente
    DROP CONSTRAINT servizio_componente_pkey;

ALTER TABLE public.servizio_componente
    ADD CONSTRAINT servizio_componente_pkey
    PRIMARY KEY (id);

-- =========================================================================
-- 4. METADATI DELLA RELAZIONE SERVIZIO-SOTTOSERVIZIO
-- =========================================================================

ALTER TABLE public.servizio_componente
    ADD COLUMN attiva boolean NOT NULL DEFAULT true,
    ADD COLUMN valido_dal timestamp with time zone NOT NULL DEFAULT now(),
    ADD COLUMN valido_al timestamp with time zone,
    ADD COLUMN relazione_primaria boolean NOT NULL DEFAULT false,
    ADD COLUMN ordine_componente integer NOT NULL DEFAULT 1,
    ADD COLUMN motivo_chiusura text,
    ADD COLUMN creato_il timestamp with time zone NOT NULL DEFAULT now(),
    ADD COLUMN aggiornato_il timestamp with time zone NOT NULL DEFAULT now();

COMMENT ON COLUMN public.servizio_componente.attiva IS
    'Indica se la relazione servizio-sottoservizio è attualmente attiva.';

COMMENT ON COLUMN public.servizio_componente.valido_dal IS
    'Data iniziale di validità della relazione.';

COMMENT ON COLUMN public.servizio_componente.valido_al IS
    'Data di chiusura della relazione storicizzata.';

COMMENT ON COLUMN public.servizio_componente.relazione_primaria IS
    'Indica l’eventuale servizio principale di riferimento del sottoservizio.';

COMMENT ON COLUMN public.servizio_componente.ordine_componente IS
    'Ordine di visualizzazione del sottoservizio nella GUI.';

COMMENT ON COLUMN public.servizio_componente.motivo_chiusura IS
    'Motivazione della chiusura logica della relazione.';

-- =========================================================================
-- 5. VINCOLI DI COERENZA DELLA GERARCHIA
-- =========================================================================

ALTER TABLE public.servizio_componente
    ADD CONSTRAINT check_servizio_componente_no_self_reference
    CHECK (
        servizio_padre_id <> servizio_figlio_id
    );

ALTER TABLE public.servizio_componente
    ADD CONSTRAINT check_servizio_componente_validita
    CHECK (
        valido_al IS NULL
        OR valido_al >= valido_dal
    );

ALTER TABLE public.servizio_componente
    ADD CONSTRAINT check_servizio_componente_stato_temporale
    CHECK (
        (
            attiva = true
            AND valido_al IS NULL
        )
        OR
        (
            attiva = false
            AND valido_al IS NOT NULL
        )
    );

ALTER TABLE public.servizio_componente
    ADD CONSTRAINT check_servizio_componente_primaria_attiva
    CHECK (
        relazione_primaria = false
        OR attiva = true
    );

ALTER TABLE public.servizio_componente
    ADD CONSTRAINT check_servizio_componente_ordine
    CHECK (
        ordine_componente > 0
    );

-- =========================================================================
-- 6. SOSTITUZIONE DELLE FOREIGN KEY CASCADE CON RESTRICT
-- =========================================================================

/*
    La cancellazione di un servizio non deve eliminare automaticamente
    la storia delle relazioni gerarchiche.

    Le FK vengono quindi convertite da ON DELETE CASCADE a
    ON DELETE RESTRICT.
*/

ALTER TABLE public.servizio_componente
    DROP CONSTRAINT servizio_componente_servizio_padre_id_fkey;

ALTER TABLE public.servizio_componente
    DROP CONSTRAINT servizio_componente_servizio_figlio_id_fkey;

ALTER TABLE public.servizio_componente
    ADD CONSTRAINT servizio_componente_servizio_padre_id_fkey
    FOREIGN KEY (servizio_padre_id)
    REFERENCES public.servizio(id)
    ON DELETE RESTRICT;

ALTER TABLE public.servizio_componente
    ADD CONSTRAINT servizio_componente_servizio_figlio_id_fkey
    FOREIGN KEY (servizio_figlio_id)
    REFERENCES public.servizio(id)
    ON DELETE RESTRICT;

-- =========================================================================
-- 7. INDICI DI UNIVOCITA' E NAVIGAZIONE
-- =========================================================================

/*
    La stessa relazione padre-figlio può comparire più volte nello
    storico, ma può risultare attiva una sola volta.
*/

CREATE UNIQUE INDEX uq_servizio_componente_relazione_attiva
    ON public.servizio_componente (
        servizio_padre_id,
        servizio_figlio_id
    )
    WHERE attiva = true;

/*
    Un sottoservizio può supportare più servizi principali, ma può
    avere al massimo un padre identificato come primario.
*/

CREATE UNIQUE INDEX uq_servizio_componente_padre_primario
    ON public.servizio_componente (
        servizio_figlio_id
    )
    WHERE attiva = true
      AND relazione_primaria = true;

/*
    Indice per recuperare rapidamente tutti i sottoservizi attivi
    di uno specifico servizio padre.
*/

CREATE INDEX idx_servizio_componente_padre_attivo
    ON public.servizio_componente (
        servizio_padre_id,
        ordine_componente
    )
    WHERE attiva = true;

/*
    Indice per risalire rapidamente da un sottoservizio ai servizi
    principali che lo utilizzano.
*/

CREATE INDEX idx_servizio_componente_figlio_attivo
    ON public.servizio_componente (
        servizio_figlio_id
    )
    WHERE attiva = true;

-- =========================================================================
-- 8. FUNZIONE DI CONTROLLO DEI CICLI
-- =========================================================================

CREATE OR REPLACE FUNCTION public.fn_check_servizio_componente_cycle()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    relazione_esclusa_id bigint;
    ciclo_rilevato boolean;
BEGIN
    NEW.aggiornato_il := now();

    IF NEW.servizio_padre_id = NEW.servizio_figlio_id THEN
        RAISE EXCEPTION
            'Un servizio non può essere componente di sé stesso.';
    END IF;

    /*
        Le relazioni storiche non attive non partecipano alla
        gerarchia corrente e non devono essere sottoposte al controllo
        di ciclicità.
    */

    IF NEW.attiva = false THEN
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        relazione_esclusa_id := OLD.id;
    ELSE
        relazione_esclusa_id := NULL;
    END IF;

    /*
        A partire dal nuovo servizio figlio vengono attraversati
        ricorsivamente tutti i discendenti attivi.

        Se tra i discendenti compare il nuovo servizio padre,
        la relazione produrrebbe un ciclo.
    */

    WITH RECURSIVE discendenti AS (
        SELECT
            sc.servizio_figlio_id
        FROM public.servizio_componente AS sc
        WHERE sc.servizio_padre_id = NEW.servizio_figlio_id
          AND sc.attiva = true
          AND (
              relazione_esclusa_id IS NULL
              OR sc.id <> relazione_esclusa_id
          )

        UNION

        SELECT
            sc.servizio_figlio_id
        FROM public.servizio_componente AS sc

        INNER JOIN discendenti AS d
            ON sc.servizio_padre_id = d.servizio_figlio_id

        WHERE sc.attiva = true
          AND (
              relazione_esclusa_id IS NULL
              OR sc.id <> relazione_esclusa_id
          )
    )
    SELECT EXISTS (
        SELECT 1
        FROM discendenti
        WHERE servizio_figlio_id = NEW.servizio_padre_id
    )
    INTO ciclo_rilevato;

    IF ciclo_rilevato THEN
        RAISE EXCEPTION
            'Relazione non valida: rilevato un ciclo nella gerarchia dei servizi.';
    END IF;

    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.fn_check_servizio_componente_cycle() IS
    'Impedisce autorelazioni e cicli nella gerarchia servizio-sottoservizio.';

-- =========================================================================
-- 9. TRIGGER DI VALIDAZIONE DELLA GERARCHIA
-- =========================================================================

DROP TRIGGER IF EXISTS trg_check_servizio_componente_cycle
ON public.servizio_componente;

CREATE TRIGGER trg_check_servizio_componente_cycle
BEFORE INSERT OR UPDATE OF
    servizio_padre_id,
    servizio_figlio_id,
    attiva,
    valido_dal,
    valido_al,
    relazione_primaria,
    ordine_componente
ON public.servizio_componente
FOR EACH ROW
EXECUTE FUNCTION public.fn_check_servizio_componente_cycle();

COMMENT ON TABLE public.servizio_componente IS
    'Relazioni storicizzabili, direzionali e acicliche tra servizi e sottoservizi.';

COMMIT;