-- =========================================================================
-- FILE: sql/30-Profili-Target-e-Attuale-FNCSDP-v1.0.sql
-- TARGET ARCHITETTURALE: ER V5.3 (36 TABELLE, 11 VISTE, 3FN RIGOROSA)
-- DESCRIZIONE: Implementazione dei Profili Target e Attuale secondo la
--              metodologia di cybersecurity assessment FNCSDP, mantenendo
--              separati catalogo, profili, controlli, mapping e misure.
-- =========================================================================
-- TIPO: MIGRAZIONE PRODUTTIVA
-- VERSIONE: 1.0.1
-- CORREZIONE: verifica finale dei trigger basata sui nomi esatti delle sei tabelle.
--
-- PRINCIPI APPLICATI:
--   1. nessuna duplicazione dell'organizzazione nell'assessment;
--   2. nessuna memorizzazione di score o gap: sono calcolati nelle viste;
--   3. relazione molti-a-molti controllo/subcategory normalizzata;
--   4. Profilo Attuale ottenuto da assessment + misure dei controlli;
--   5. stesso insieme di controlli e mapping del Profilo Target;
--   6. copertura su scala 0, 0.2, 0.4, 0.6, 0.8, 1;
--   7. maturita CMMI da 1 a 5, non applicabile con copertura nulla;
--   8. RLS, audit, archiviazione logica e blocco DELETE coerenti col progetto.
-- =========================================================================

BEGIN;

-- =========================================================================
-- 1. VERIFICHE PRELIMINARI BLOCCANTI
-- =========================================================================

DO $$
DECLARE
    v_tabelle integer;
    v_viste integer;
BEGIN
    SELECT count(*) INTO v_tabelle
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE';

    SELECT count(*) INTO v_viste
    FROM information_schema.views
    WHERE table_schema = 'public';

    IF v_tabelle <> 30 THEN
        RAISE EXCEPTION 'Numero tabelle public inatteso: % invece di 30.', v_tabelle;
    END IF;

    IF v_viste <> 7 THEN
        RAISE EXCEPTION 'Numero viste public inatteso: % invece di 7.', v_viste;
    END IF;

    IF to_regclass('public.organizzazione') IS NULL
       OR to_regclass('public.responsabile') IS NULL
       OR to_regclass('public.audit_log') IS NULL THEN
        RAISE EXCEPTION 'Prerequisiti mancanti: organizzazione, responsabile o audit_log.';
    END IF;

    IF to_regprocedure('public.fn_accesso_operativo()') IS NULL
       OR to_regprocedure('public.fn_gestisci_archiviazione_logica()') IS NULL
       OR to_regprocedure('public.fn_blocca_cancellazione_fisica()') IS NULL THEN
        RAISE EXCEPTION 'Prerequisiti mancanti: funzioni di accesso, archiviazione o blocco DELETE.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname IN (
              'fncsdp_subcategory',
              'profilo_target_fncsdp',
              'controllo_target_fncsdp',
              'controllo_target_subcategory_fncsdp',
              'assessment_fncsdp',
              'misura_controllo_fncsdp'
          )
    ) THEN
        RAISE EXCEPTION 'Sono gia presenti oggetti FNCSDP: interrompere e verificare lo stato del database.';
    END IF;
END;
$$;

-- =========================================================================
-- 2. CATALOGO DELLE SUBCATEGORY FNCSDP
--
-- Function e Category non vengono duplicate: sono ricavabili dal codice
-- canonico della Subcategory (es. ID.AM-1 -> Function ID, Category ID.AM).
-- =========================================================================

CREATE TABLE public.fncsdp_subcategory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versione_framework varchar(10) NOT NULL DEFAULT '2.0',
    codice varchar(20) NOT NULL,
    descrizione text NOT NULL,
    ordine integer NOT NULL,
    attiva boolean NOT NULL DEFAULT true,
    archiviato_da uuid,
    archiviato_il timestamptz,
    motivo_archiviazione text,
    creato_il timestamptz NOT NULL DEFAULT clock_timestamp(),
    aggiornato_il timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT uq_fncsdp_subcategory_versione_codice
        UNIQUE (versione_framework, codice),

    CONSTRAINT ck_fncsdp_subcategory_codice
        CHECK (codice ~ '^[A-Z]{2}(\.[A-Z]{2,3})?-[0-9]+$'),

    CONSTRAINT ck_fncsdp_subcategory_ordine
        CHECK (ordine > 0),

    CONSTRAINT ck_fncsdp_subcategory_archiviazione
        CHECK (
            (attiva IS TRUE AND archiviato_il IS NULL AND archiviato_da IS NULL AND motivo_archiviazione IS NULL)
            OR
            (attiva IS FALSE AND archiviato_il IS NOT NULL AND motivo_archiviazione IS NOT NULL AND btrim(motivo_archiviazione) <> '')
        )
);

COMMENT ON TABLE public.fncsdp_subcategory IS
    'Catalogo normalizzato delle Subcategory FNCSDP utilizzate dal modulo di assessment.';

-- =========================================================================
-- 3. PROFILO TARGET
-- =========================================================================

CREATE TABLE public.profilo_target_fncsdp (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizzazione_id integer NOT NULL,
    codice varchar(40) NOT NULL,
    nome varchar(160) NOT NULL,
    descrizione text,
    perimetro text NOT NULL,
    versione integer NOT NULL DEFAULT 1,
    stato varchar(20) NOT NULL DEFAULT 'BOZZA',
    creato_da uuid DEFAULT auth.uid(),
    approvato_da uuid,
    approvato_il timestamptz,
    attiva boolean NOT NULL DEFAULT true,
    archiviato_da uuid,
    archiviato_il timestamptz,
    motivo_archiviazione text,
    creato_il timestamptz NOT NULL DEFAULT clock_timestamp(),
    aggiornato_il timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_profilo_target_fncsdp_organizzazione
        FOREIGN KEY (organizzazione_id)
        REFERENCES public.organizzazione(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_profilo_target_fncsdp_organizzazione_codice
        UNIQUE (organizzazione_id, codice),

    CONSTRAINT ck_profilo_target_fncsdp_codice
        CHECK (codice ~ '^[A-Z0-9][A-Z0-9_-]{2,39}$'),

    CONSTRAINT ck_profilo_target_fncsdp_versione
        CHECK (versione > 0),

    CONSTRAINT ck_profilo_target_fncsdp_stato
        CHECK (stato IN ('BOZZA', 'APPROVATO')),

    CONSTRAINT ck_profilo_target_fncsdp_approvazione
        CHECK (
            (stato = 'BOZZA' AND approvato_il IS NULL AND approvato_da IS NULL)
            OR
            (stato = 'APPROVATO' AND approvato_il IS NOT NULL)
        ),

    CONSTRAINT ck_profilo_target_fncsdp_archiviazione
        CHECK (
            (attiva IS TRUE AND archiviato_il IS NULL AND archiviato_da IS NULL AND motivo_archiviazione IS NULL)
            OR
            (attiva IS FALSE AND archiviato_il IS NOT NULL AND motivo_archiviazione IS NOT NULL AND btrim(motivo_archiviazione) <> '')
        )
);

COMMENT ON TABLE public.profilo_target_fncsdp IS
    'Testata del Profilo Target FNCSDP definito per un soggetto NIS2.';

-- =========================================================================
-- 4. CONTROLLI DEL PROFILO TARGET
-- =========================================================================

CREATE TABLE public.controllo_target_fncsdp (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profilo_target_id bigint NOT NULL,
    codice varchar(50) NOT NULL,
    nome varchar(200) NOT NULL,
    descrizione text NOT NULL,
    copertura_target numeric(3,2) NOT NULL DEFAULT 1.00,
    ordine integer NOT NULL,
    attiva boolean NOT NULL DEFAULT true,
    archiviato_da uuid,
    archiviato_il timestamptz,
    motivo_archiviazione text,
    creato_il timestamptz NOT NULL DEFAULT clock_timestamp(),
    aggiornato_il timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_controllo_target_fncsdp_profilo
        FOREIGN KEY (profilo_target_id)
        REFERENCES public.profilo_target_fncsdp(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_controllo_target_fncsdp_profilo_codice
        UNIQUE (profilo_target_id, codice),

    CONSTRAINT ck_controllo_target_fncsdp_codice
        CHECK (codice ~ '^[A-Z0-9][A-Z0-9_.-]{2,49}$'),

    CONSTRAINT ck_controllo_target_fncsdp_copertura
        CHECK (copertura_target IN (0.00, 0.20, 0.40, 0.60, 0.80, 1.00)),

    CONSTRAINT ck_controllo_target_fncsdp_ordine
        CHECK (ordine > 0),

    CONSTRAINT ck_controllo_target_fncsdp_archiviazione
        CHECK (
            (attiva IS TRUE AND archiviato_il IS NULL AND archiviato_da IS NULL AND motivo_archiviazione IS NULL)
            OR
            (attiva IS FALSE AND archiviato_il IS NOT NULL AND motivo_archiviazione IS NOT NULL AND btrim(motivo_archiviazione) <> '')
        )
);

COMMENT ON TABLE public.controllo_target_fncsdp IS
    'Controlli di sicurezza del Profilo Target e relativa copertura desiderata.';

-- =========================================================================
-- 5. MATRICE CONTROLLO - SUBCATEGORY
--
-- Il peso appartiene alla coppia controllo/subcategory e non al controllo.
-- =========================================================================

CREATE TABLE public.controllo_target_subcategory_fncsdp (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    controllo_target_id bigint NOT NULL,
    subcategory_id bigint NOT NULL,
    peso numeric(4,3) NOT NULL DEFAULT 1.000,
    attiva boolean NOT NULL DEFAULT true,
    archiviato_da uuid,
    archiviato_il timestamptz,
    motivo_archiviazione text,
    creato_il timestamptz NOT NULL DEFAULT clock_timestamp(),
    aggiornato_il timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_controllo_subcategory_fncsdp_controllo
        FOREIGN KEY (controllo_target_id)
        REFERENCES public.controllo_target_fncsdp(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_controllo_subcategory_fncsdp_subcategory
        FOREIGN KEY (subcategory_id)
        REFERENCES public.fncsdp_subcategory(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_controllo_subcategory_fncsdp
        UNIQUE (controllo_target_id, subcategory_id),

    CONSTRAINT ck_controllo_subcategory_fncsdp_peso
        CHECK (peso > 0.000 AND peso <= 1.000),

    CONSTRAINT ck_controllo_subcategory_fncsdp_archiviazione
        CHECK (
            (attiva IS TRUE AND archiviato_il IS NULL AND archiviato_da IS NULL AND motivo_archiviazione IS NULL)
            OR
            (attiva IS FALSE AND archiviato_il IS NOT NULL AND motivo_archiviazione IS NOT NULL AND btrim(motivo_archiviazione) <> '')
        )
);

COMMENT ON TABLE public.controllo_target_subcategory_fncsdp IS
    'Matrice normalizzata che associa i controlli del Target alle Subcategory FNCSDP con il relativo peso.';

-- =========================================================================
-- 6. ASSESSMENT E PROFILO ATTUALE
--
-- L'organizzazione non viene duplicata: e determinata dal Profilo Target.
-- =========================================================================

CREATE TABLE public.assessment_fncsdp (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profilo_target_id bigint NOT NULL,
    codice varchar(40) NOT NULL,
    nome varchar(160) NOT NULL,
    data_assessment date NOT NULL DEFAULT current_date,
    responsabile_assessor_id integer,
    note text,
    stato varchar(20) NOT NULL DEFAULT 'BOZZA',
    creato_da uuid DEFAULT auth.uid(),
    completato_da uuid,
    completato_il timestamptz,
    attiva boolean NOT NULL DEFAULT true,
    archiviato_da uuid,
    archiviato_il timestamptz,
    motivo_archiviazione text,
    creato_il timestamptz NOT NULL DEFAULT clock_timestamp(),
    aggiornato_il timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_assessment_fncsdp_profilo
        FOREIGN KEY (profilo_target_id)
        REFERENCES public.profilo_target_fncsdp(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_assessment_fncsdp_assessor
        FOREIGN KEY (responsabile_assessor_id)
        REFERENCES public.responsabile(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_assessment_fncsdp_profilo_codice
        UNIQUE (profilo_target_id, codice),

    CONSTRAINT ck_assessment_fncsdp_codice
        CHECK (codice ~ '^[A-Z0-9][A-Z0-9_-]{2,39}$'),

    CONSTRAINT ck_assessment_fncsdp_stato
        CHECK (stato IN ('BOZZA', 'COMPLETATO')),

    CONSTRAINT ck_assessment_fncsdp_completamento
        CHECK (
            (stato = 'BOZZA' AND completato_il IS NULL AND completato_da IS NULL)
            OR
            (stato = 'COMPLETATO' AND completato_il IS NOT NULL)
        ),

    CONSTRAINT ck_assessment_fncsdp_archiviazione
        CHECK (
            (attiva IS TRUE AND archiviato_il IS NULL AND archiviato_da IS NULL AND motivo_archiviazione IS NULL)
            OR
            (attiva IS FALSE AND archiviato_il IS NOT NULL AND motivo_archiviazione IS NOT NULL AND btrim(motivo_archiviazione) <> '')
        )
);

COMMENT ON TABLE public.assessment_fncsdp IS
    'Istanza periodica di assessment associata a un Profilo Target approvato.';

CREATE TABLE public.misura_controllo_fncsdp (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id bigint NOT NULL,
    controllo_target_id bigint NOT NULL,
    risposta text,
    note_copertura text,
    copertura_attuale numeric(3,2),
    note_maturita text,
    livello_maturita smallint,
    evidenze text,
    note text,
    attiva boolean NOT NULL DEFAULT true,
    archiviato_da uuid,
    archiviato_il timestamptz,
    motivo_archiviazione text,
    creato_il timestamptz NOT NULL DEFAULT clock_timestamp(),
    aggiornato_il timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT fk_misura_controllo_fncsdp_assessment
        FOREIGN KEY (assessment_id)
        REFERENCES public.assessment_fncsdp(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_misura_controllo_fncsdp_controllo
        FOREIGN KEY (controllo_target_id)
        REFERENCES public.controllo_target_fncsdp(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_misura_controllo_fncsdp
        UNIQUE (assessment_id, controllo_target_id),

    CONSTRAINT ck_misura_controllo_fncsdp_copertura
        CHECK (
            copertura_attuale IS NULL
            OR copertura_attuale IN (0.00, 0.20, 0.40, 0.60, 0.80, 1.00)
        ),

    CONSTRAINT ck_misura_controllo_fncsdp_maturita
        CHECK (livello_maturita IS NULL OR livello_maturita BETWEEN 1 AND 5),

    CONSTRAINT ck_misura_controllo_fncsdp_zero_maturita
        CHECK (copertura_attuale IS DISTINCT FROM 0.00 OR livello_maturita IS NULL),

    CONSTRAINT ck_misura_controllo_fncsdp_archiviazione
        CHECK (
            (attiva IS TRUE AND archiviato_il IS NULL AND archiviato_da IS NULL AND motivo_archiviazione IS NULL)
            OR
            (attiva IS FALSE AND archiviato_il IS NOT NULL AND motivo_archiviazione IS NOT NULL AND btrim(motivo_archiviazione) <> '')
        )
);

COMMENT ON TABLE public.misura_controllo_fncsdp IS
    'Misure del Profilo Attuale: risposta, copertura, maturita, evidenze e note per ciascun controllo.';

-- =========================================================================
-- 7. INDICI
-- =========================================================================

CREATE INDEX idx_fncsdp_subcategory_ordine
    ON public.fncsdp_subcategory (ordine)
    WHERE attiva IS TRUE;

CREATE INDEX idx_profilo_target_fncsdp_organizzazione
    ON public.profilo_target_fncsdp (organizzazione_id, stato, attiva);

CREATE INDEX idx_controllo_target_fncsdp_profilo
    ON public.controllo_target_fncsdp (profilo_target_id, ordine)
    WHERE attiva IS TRUE;

CREATE INDEX idx_controllo_subcategory_fncsdp_subcategory
    ON public.controllo_target_subcategory_fncsdp (subcategory_id, controllo_target_id)
    WHERE attiva IS TRUE;

CREATE INDEX idx_assessment_fncsdp_profilo_data
    ON public.assessment_fncsdp (profilo_target_id, data_assessment DESC, id DESC)
    WHERE attiva IS TRUE;

CREATE INDEX idx_misura_controllo_fncsdp_assessment
    ON public.misura_controllo_fncsdp (assessment_id, controllo_target_id)
    WHERE attiva IS TRUE;

-- =========================================================================
-- 8. POPOLAMENTO DEL CATALOGO FNCSDP - ASSET MANAGEMENT ID.AM
--
-- Le sei Subcategory sono coerenti con il perimetro del Project Work.
-- =========================================================================

INSERT INTO public.fncsdp_subcategory (
    versione_framework,
    codice,
    descrizione,
    ordine
)
VALUES
    ('2.0', 'ID.AM-1', 'Sono censiti i sistemi e gli apparati fisici in uso nell''organizzazione.', 1),
    ('2.0', 'ID.AM-2', 'Sono censite le piattaforme e le applicazioni software in uso nell''organizzazione.', 2),
    ('2.0', 'ID.AM-3', 'I flussi di dati e comunicazioni inerenti l''organizzazione sono identificati.', 3),
    ('2.0', 'ID.AM-4', 'I sistemi informativi esterni all''organizzazione sono catalogati.', 4),
    ('2.0', 'ID.AM-5', 'Le risorse sono prioritizzate in base alla loro classificazione, criticita e valore per il business dell''organizzazione.', 5),
    ('2.0', 'ID.AM-6', 'Sono definiti e resi noti ruoli e responsabilita inerenti la cybersecurity per tutto il personale e per eventuali terze parti rilevanti.', 6);

-- =========================================================================
-- 9. FUNZIONI DI SERVIZIO E VALIDAZIONE
-- =========================================================================

CREATE OR REPLACE FUNCTION public.fn_touch_fncsdp()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
    NEW.aggiornato_il := clock_timestamp();
    RETURN NEW;
END;
$$;

ALTER FUNCTION public.fn_touch_fncsdp() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_touch_fncsdp() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.fn_valida_mapping_fncsdp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_stato_nuovo text;
    v_stato_precedente text;
BEGIN
    SELECT pt.stato
    INTO v_stato_nuovo
    FROM public.controllo_target_fncsdp c
    JOIN public.profilo_target_fncsdp pt ON pt.id = c.profilo_target_id
    WHERE c.id = NEW.controllo_target_id;

    IF TG_OP = 'UPDATE' THEN
        SELECT pt.stato
        INTO v_stato_precedente
        FROM public.controllo_target_fncsdp c
        JOIN public.profilo_target_fncsdp pt ON pt.id = c.profilo_target_id
        WHERE c.id = OLD.controllo_target_id;
    END IF;

    IF v_stato_nuovo IS NULL THEN
        RAISE EXCEPTION 'Controllo Target non valido.';
    END IF;

    IF v_stato_nuovo = 'APPROVATO' OR v_stato_precedente = 'APPROVATO' THEN
        RAISE EXCEPTION 'Il Profilo Target approvato non puo essere modificato.';
    END IF;

    RETURN NEW;
END;
$$;

ALTER FUNCTION public.fn_valida_mapping_fncsdp() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_valida_mapping_fncsdp() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.fn_valida_controllo_target_fncsdp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_stato_nuovo text;
    v_stato_precedente text;
BEGIN
    SELECT stato INTO v_stato_nuovo
    FROM public.profilo_target_fncsdp
    WHERE id = NEW.profilo_target_id;

    IF TG_OP = 'UPDATE' THEN
        SELECT stato INTO v_stato_precedente
        FROM public.profilo_target_fncsdp
        WHERE id = OLD.profilo_target_id;
    END IF;

    IF v_stato_nuovo IS NULL THEN
        RAISE EXCEPTION 'Profilo Target non valido.';
    END IF;

    IF v_stato_nuovo = 'APPROVATO' OR v_stato_precedente = 'APPROVATO' THEN
        RAISE EXCEPTION 'Il Profilo Target approvato non puo essere modificato.';
    END IF;

    NEW.aggiornato_il := clock_timestamp();
    RETURN NEW;
END;
$$;

ALTER FUNCTION public.fn_valida_controllo_target_fncsdp() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_valida_controllo_target_fncsdp() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.fn_valida_profilo_target_fncsdp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF TG_OP = 'INSERT'
       AND NEW.stato <> 'BOZZA'
       AND coalesce(current_setting('app.fncsdp_target_approval', true), '0') <> '1' THEN
        RAISE EXCEPTION 'Un Profilo Target deve essere creato nello stato BOZZA.';
    END IF;

    IF TG_OP = 'UPDATE' AND OLD.stato = 'APPROVATO' THEN
        IF ROW(
            NEW.organizzazione_id,
            NEW.codice,
            NEW.nome,
            NEW.descrizione,
            NEW.perimetro,
            NEW.versione,
            NEW.stato,
            NEW.approvato_da,
            NEW.approvato_il
        ) IS DISTINCT FROM ROW(
            OLD.organizzazione_id,
            OLD.codice,
            OLD.nome,
            OLD.descrizione,
            OLD.perimetro,
            OLD.versione,
            OLD.stato,
            OLD.approvato_da,
            OLD.approvato_il
        ) THEN
            RAISE EXCEPTION 'Il Profilo Target approvato e immutabile.';
        END IF;
    END IF;

    IF TG_OP = 'UPDATE'
       AND OLD.stato = 'BOZZA'
       AND NEW.stato = 'APPROVATO'
       AND coalesce(current_setting('app.fncsdp_target_approval', true), '0') <> '1' THEN
        RAISE EXCEPTION 'Usare la funzione fn_approva_profilo_target_fncsdp().';
    END IF;

    NEW.aggiornato_il := clock_timestamp();
    RETURN NEW;
END;
$$;

ALTER FUNCTION public.fn_valida_profilo_target_fncsdp() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_valida_profilo_target_fncsdp() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.fn_valida_assessment_fncsdp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_stato_target text;
BEGIN
    SELECT stato
    INTO v_stato_target
    FROM public.profilo_target_fncsdp
    WHERE id = NEW.profilo_target_id
      AND attiva IS TRUE;

    IF v_stato_target IS DISTINCT FROM 'APPROVATO' THEN
        RAISE EXCEPTION 'L''assessment richiede un Profilo Target attivo e approvato.';
    END IF;

    IF NEW.responsabile_assessor_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM public.responsabile r
           JOIN public.profilo_target_fncsdp pt
             ON pt.id = NEW.profilo_target_id
            AND pt.organizzazione_id = r.organizzazione_id
           WHERE r.id = NEW.responsabile_assessor_id
             AND r.attiva IS TRUE
       ) THEN
        RAISE EXCEPTION 'Assessor non valido, non attivo o appartenente a un altro soggetto NIS2.';
    END IF;

    IF TG_OP = 'UPDATE' AND NEW.profilo_target_id IS DISTINCT FROM OLD.profilo_target_id THEN
        RAISE EXCEPTION 'Il Profilo Target di un assessment non puo essere modificato.';
    END IF;

    IF TG_OP = 'INSERT'
       AND NEW.stato <> 'BOZZA'
       AND coalesce(current_setting('app.fncsdp_assessment_completion', true), '0') <> '1' THEN
        RAISE EXCEPTION 'Un assessment deve essere creato nello stato BOZZA.';
    END IF;

    IF TG_OP = 'UPDATE' AND OLD.stato = 'COMPLETATO' THEN
        IF ROW(
            NEW.profilo_target_id,
            NEW.codice,
            NEW.nome,
            NEW.data_assessment,
            NEW.responsabile_assessor_id,
            NEW.note,
            NEW.stato,
            NEW.completato_da,
            NEW.completato_il
        ) IS DISTINCT FROM ROW(
            OLD.profilo_target_id,
            OLD.codice,
            OLD.nome,
            OLD.data_assessment,
            OLD.responsabile_assessor_id,
            OLD.note,
            OLD.stato,
            OLD.completato_da,
            OLD.completato_il
        ) THEN
            RAISE EXCEPTION 'L''assessment completato e immutabile.';
        END IF;
    END IF;

    IF TG_OP = 'UPDATE'
       AND OLD.stato = 'BOZZA'
       AND NEW.stato = 'COMPLETATO'
       AND coalesce(current_setting('app.fncsdp_assessment_completion', true), '0') <> '1' THEN
        RAISE EXCEPTION 'Usare la funzione fn_completa_assessment_fncsdp().';
    END IF;

    NEW.aggiornato_il := clock_timestamp();
    RETURN NEW;
END;
$$;

ALTER FUNCTION public.fn_valida_assessment_fncsdp() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_valida_assessment_fncsdp() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.fn_valida_misura_controllo_fncsdp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_target_assessment bigint;
    v_target_controllo bigint;
    v_stato_assessment text;
    v_stato_assessment_precedente text;
BEGIN
    SELECT profilo_target_id, stato
    INTO v_target_assessment, v_stato_assessment
    FROM public.assessment_fncsdp
    WHERE id = NEW.assessment_id
      AND attiva IS TRUE;

    SELECT profilo_target_id
    INTO v_target_controllo
    FROM public.controllo_target_fncsdp
    WHERE id = NEW.controllo_target_id
      AND attiva IS TRUE;

    IF TG_OP = 'UPDATE' THEN
        SELECT stato
        INTO v_stato_assessment_precedente
        FROM public.assessment_fncsdp
        WHERE id = OLD.assessment_id;
    END IF;

    IF v_target_assessment IS NULL OR v_target_controllo IS NULL THEN
        RAISE EXCEPTION 'Assessment o controllo Target non valido.';
    END IF;

    IF TG_OP = 'UPDATE'
       AND (
           NEW.assessment_id IS DISTINCT FROM OLD.assessment_id
           OR NEW.controllo_target_id IS DISTINCT FROM OLD.controllo_target_id
       ) THEN
        RAISE EXCEPTION 'Assessment e controllo della misura non possono essere modificati.';
    END IF;

    IF v_target_assessment <> v_target_controllo THEN
        RAISE EXCEPTION 'Il controllo non appartiene al Profilo Target dell''assessment.';
    END IF;

    IF v_stato_assessment = 'COMPLETATO' OR v_stato_assessment_precedente = 'COMPLETATO' THEN
        RAISE EXCEPTION 'L''assessment completato non puo essere modificato.';
    END IF;

    IF NEW.copertura_attuale = 0.00 THEN
        NEW.livello_maturita := NULL;
    END IF;

    NEW.aggiornato_il := clock_timestamp();
    RETURN NEW;
END;
$$;

ALTER FUNCTION public.fn_valida_misura_controllo_fncsdp() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_valida_misura_controllo_fncsdp() FROM PUBLIC, anon, authenticated;

-- =========================================================================
-- 10. FUNZIONI TRANSAZIONALI APPLICATIVE
-- =========================================================================

CREATE OR REPLACE FUNCTION public.fn_crea_profilo_target_fncsdp(
    p_organizzazione_id integer,
    p_codice text,
    p_nome text,
    p_descrizione text,
    p_perimetro text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
    v_profilo_id bigint;
    v_subcategory record;
    v_controllo_id bigint;
    v_codice text;
    v_nome text;
    v_descrizione text;
BEGIN
    IF NOT public.fn_accesso_operativo() THEN
        RAISE EXCEPTION 'Accesso operativo non autorizzato.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.organizzazione
        WHERE id = p_organizzazione_id
          AND attiva IS TRUE
    ) THEN
        RAISE EXCEPTION 'Soggetto NIS2 non valido o non attivo.';
    END IF;

    v_codice := upper(btrim(coalesce(p_codice, '')));
    v_nome := btrim(coalesce(p_nome, ''));
    v_descrizione := nullif(btrim(coalesce(p_descrizione, '')), '');

    IF v_codice !~ '^[A-Z0-9][A-Z0-9_-]{2,39}$' THEN
        RAISE EXCEPTION 'Codice Profilo Target non valido.';
    END IF;

    IF length(v_nome) < 3 THEN
        RAISE EXCEPTION 'Nome Profilo Target obbligatorio.';
    END IF;

    IF length(btrim(coalesce(p_perimetro, ''))) < 10 THEN
        RAISE EXCEPTION 'Descrivere il perimetro del Profilo Target con almeno 10 caratteri.';
    END IF;

    INSERT INTO public.profilo_target_fncsdp (
        organizzazione_id,
        codice,
        nome,
        descrizione,
        perimetro,
        creato_da
    )
    VALUES (
        p_organizzazione_id,
        v_codice,
        v_nome,
        v_descrizione,
        btrim(p_perimetro),
        auth.uid()
    )
    RETURNING id INTO v_profilo_id;

    FOR v_subcategory IN
        SELECT id, codice, descrizione, ordine
        FROM public.fncsdp_subcategory
        WHERE versione_framework = '2.0'
          AND codice BETWEEN 'ID.AM-1' AND 'ID.AM-6'
          AND attiva IS TRUE
        ORDER BY ordine
    LOOP
        INSERT INTO public.controllo_target_fncsdp (
            profilo_target_id,
            codice,
            nome,
            descrizione,
            copertura_target,
            ordine
        )
        VALUES (
            v_profilo_id,
            'CTRL-' || replace(v_subcategory.codice, '.', '-'),
            CASE v_subcategory.codice
                WHEN 'ID.AM-1' THEN 'Inventario dei sistemi e apparati fisici'
                WHEN 'ID.AM-2' THEN 'Inventario delle piattaforme e applicazioni software'
                WHEN 'ID.AM-3' THEN 'Mappatura dei flussi di dati e comunicazioni'
                WHEN 'ID.AM-4' THEN 'Catalogo dei sistemi informativi esterni'
                WHEN 'ID.AM-5' THEN 'Classificazione e prioritizzazione delle risorse'
                WHEN 'ID.AM-6' THEN 'Assegnazione di ruoli e responsabilita cybersecurity'
            END,
            CASE v_subcategory.codice
                WHEN 'ID.AM-1' THEN 'Mantenere aggiornato il censimento dei sistemi e degli apparati fisici compresi nel perimetro.'
                WHEN 'ID.AM-2' THEN 'Mantenere aggiornato il censimento delle piattaforme e delle applicazioni software comprese nel perimetro.'
                WHEN 'ID.AM-3' THEN 'Identificare e documentare i principali flussi di dati e comunicazioni associati ai servizi e agli asset censiti.'
                WHEN 'ID.AM-4' THEN 'Catalogare i sistemi informativi esterni e le dipendenze da fornitori o servizi terzi rilevanti.'
                WHEN 'ID.AM-5' THEN 'Classificare e prioritizzare le risorse secondo criticita, valore e contributo ai servizi del soggetto NIS2.'
                WHEN 'ID.AM-6' THEN 'Definire e mantenere tracciati ruoli, responsabilita e incarichi cybersecurity interni ed esterni.'
            END,
            1.00,
            v_subcategory.ordine
        )
        RETURNING id INTO v_controllo_id;

        INSERT INTO public.controllo_target_subcategory_fncsdp (
            controllo_target_id,
            subcategory_id,
            peso
        )
        VALUES (
            v_controllo_id,
            v_subcategory.id,
            1.000
        );
    END LOOP;

    RETURN v_profilo_id;
END;
$$;

ALTER FUNCTION public.fn_crea_profilo_target_fncsdp(integer, text, text, text, text) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_crea_profilo_target_fncsdp(integer, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_crea_profilo_target_fncsdp(integer, text, text, text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.fn_approva_profilo_target_fncsdp(p_profilo_target_id bigint)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
    v_controlli integer;
    v_senza_mapping integer;
BEGIN
    IF NOT public.fn_accesso_operativo() THEN
        RAISE EXCEPTION 'Accesso operativo non autorizzato.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.profilo_target_fncsdp
        WHERE id = p_profilo_target_id
          AND attiva IS TRUE
          AND stato = 'BOZZA'
    ) THEN
        RAISE EXCEPTION 'Profilo Target non disponibile oppure gia approvato.';
    END IF;

    SELECT count(*)
    INTO v_controlli
    FROM public.controllo_target_fncsdp
    WHERE profilo_target_id = p_profilo_target_id
      AND attiva IS TRUE;

    IF v_controlli = 0 THEN
        RAISE EXCEPTION 'Il Profilo Target non contiene controlli attivi.';
    END IF;

    SELECT count(*)
    INTO v_senza_mapping
    FROM public.controllo_target_fncsdp c
    WHERE c.profilo_target_id = p_profilo_target_id
      AND c.attiva IS TRUE
      AND NOT EXISTS (
          SELECT 1
          FROM public.controllo_target_subcategory_fncsdp m
          WHERE m.controllo_target_id = c.id
            AND m.attiva IS TRUE
      );

    IF v_senza_mapping > 0 THEN
        RAISE EXCEPTION '% controlli non possiedono una Subcategory associata.', v_senza_mapping;
    END IF;

    PERFORM set_config('app.fncsdp_target_approval', '1', true);

    UPDATE public.profilo_target_fncsdp
    SET
        stato = 'APPROVATO',
        approvato_da = auth.uid(),
        approvato_il = clock_timestamp(),
        aggiornato_il = clock_timestamp()
    WHERE id = p_profilo_target_id;

    RETURN p_profilo_target_id;
END;
$$;

ALTER FUNCTION public.fn_approva_profilo_target_fncsdp(bigint) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_approva_profilo_target_fncsdp(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_approva_profilo_target_fncsdp(bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.fn_crea_assessment_fncsdp(
    p_profilo_target_id bigint,
    p_codice text,
    p_nome text,
    p_data_assessment date DEFAULT current_date,
    p_responsabile_assessor_id integer DEFAULT NULL,
    p_note text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
    v_assessment_id bigint;
    v_codice text;
    v_nome text;
BEGIN
    IF NOT public.fn_accesso_operativo() THEN
        RAISE EXCEPTION 'Accesso operativo non autorizzato.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.profilo_target_fncsdp
        WHERE id = p_profilo_target_id
          AND stato = 'APPROVATO'
          AND attiva IS TRUE
    ) THEN
        RAISE EXCEPTION 'Il Profilo Target deve essere attivo e approvato.';
    END IF;

    IF p_responsabile_assessor_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM public.responsabile r
           JOIN public.profilo_target_fncsdp pt
             ON pt.id = p_profilo_target_id
            AND pt.organizzazione_id = r.organizzazione_id
           WHERE r.id = p_responsabile_assessor_id
             AND r.attiva IS TRUE
       ) THEN
        RAISE EXCEPTION 'Assessor non valido, non attivo o appartenente a un altro soggetto NIS2.';
    END IF;

    v_codice := upper(btrim(coalesce(p_codice, '')));
    v_nome := btrim(coalesce(p_nome, ''));

    IF v_codice !~ '^[A-Z0-9][A-Z0-9_-]{2,39}$' THEN
        RAISE EXCEPTION 'Codice assessment non valido.';
    END IF;

    IF length(v_nome) < 3 THEN
        RAISE EXCEPTION 'Nome assessment obbligatorio.';
    END IF;

    INSERT INTO public.assessment_fncsdp (
        profilo_target_id,
        codice,
        nome,
        data_assessment,
        responsabile_assessor_id,
        note,
        creato_da
    )
    VALUES (
        p_profilo_target_id,
        v_codice,
        v_nome,
        coalesce(p_data_assessment, current_date),
        p_responsabile_assessor_id,
        nullif(btrim(coalesce(p_note, '')), ''),
        auth.uid()
    )
    RETURNING id INTO v_assessment_id;

    INSERT INTO public.misura_controllo_fncsdp (
        assessment_id,
        controllo_target_id
    )
    SELECT
        v_assessment_id,
        c.id
    FROM public.controllo_target_fncsdp c
    WHERE c.profilo_target_id = p_profilo_target_id
      AND c.attiva IS TRUE
    ORDER BY c.ordine;

    RETURN v_assessment_id;
END;
$$;

ALTER FUNCTION public.fn_crea_assessment_fncsdp(bigint, text, text, date, integer, text) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_crea_assessment_fncsdp(bigint, text, text, date, integer, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_crea_assessment_fncsdp(bigint, text, text, date, integer, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.fn_completa_assessment_fncsdp(p_assessment_id bigint)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
    v_attesi integer;
    v_misure integer;
    v_incomplete integer;
BEGIN
    IF NOT public.fn_accesso_operativo() THEN
        RAISE EXCEPTION 'Accesso operativo non autorizzato.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.assessment_fncsdp
        WHERE id = p_assessment_id
          AND stato = 'BOZZA'
          AND attiva IS TRUE
    ) THEN
        RAISE EXCEPTION 'Assessment non disponibile oppure gia completato.';
    END IF;

    SELECT count(*)
    INTO v_attesi
    FROM public.assessment_fncsdp a
    JOIN public.controllo_target_fncsdp c
      ON c.profilo_target_id = a.profilo_target_id
     AND c.attiva IS TRUE
    WHERE a.id = p_assessment_id;

    SELECT count(*)
    INTO v_misure
    FROM public.misura_controllo_fncsdp
    WHERE assessment_id = p_assessment_id
      AND attiva IS TRUE;

    IF v_attesi = 0 OR v_misure <> v_attesi THEN
        RAISE EXCEPTION 'Numero misure incoerente: attese %, presenti %.', v_attesi, v_misure;
    END IF;

    SELECT count(*)
    INTO v_incomplete
    FROM public.misura_controllo_fncsdp
    WHERE assessment_id = p_assessment_id
      AND attiva IS TRUE
      AND (
          copertura_attuale IS NULL
          OR (copertura_attuale > 0.00 AND livello_maturita IS NULL)
          OR (copertura_attuale = 0.00 AND livello_maturita IS NOT NULL)
      );

    IF v_incomplete > 0 THEN
        RAISE EXCEPTION '% misure non sono complete o coerenti.', v_incomplete;
    END IF;

    PERFORM set_config('app.fncsdp_assessment_completion', '1', true);

    UPDATE public.assessment_fncsdp
    SET
        stato = 'COMPLETATO',
        completato_da = auth.uid(),
        completato_il = clock_timestamp(),
        aggiornato_il = clock_timestamp()
    WHERE id = p_assessment_id;

    RETURN p_assessment_id;
END;
$$;

ALTER FUNCTION public.fn_completa_assessment_fncsdp(bigint) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_completa_assessment_fncsdp(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_completa_assessment_fncsdp(bigint) TO authenticated;

-- =========================================================================
-- 11. TRIGGER DI VALIDAZIONE, TIMESTAMP E ARCHIVIAZIONE
-- =========================================================================

CREATE TRIGGER trg_valida_profilo_target_fncsdp
BEFORE INSERT OR UPDATE
ON public.profilo_target_fncsdp
FOR EACH ROW
EXECUTE FUNCTION public.fn_valida_profilo_target_fncsdp();

CREATE TRIGGER trg_valida_controllo_target_fncsdp
BEFORE INSERT OR UPDATE
ON public.controllo_target_fncsdp
FOR EACH ROW
EXECUTE FUNCTION public.fn_valida_controllo_target_fncsdp();

CREATE TRIGGER trg_valida_mapping_fncsdp
BEFORE INSERT OR UPDATE
ON public.controllo_target_subcategory_fncsdp
FOR EACH ROW
EXECUTE FUNCTION public.fn_valida_mapping_fncsdp();

CREATE TRIGGER trg_valida_assessment_fncsdp
BEFORE INSERT OR UPDATE
ON public.assessment_fncsdp
FOR EACH ROW
EXECUTE FUNCTION public.fn_valida_assessment_fncsdp();

CREATE TRIGGER trg_valida_misura_controllo_fncsdp
BEFORE INSERT OR UPDATE
ON public.misura_controllo_fncsdp
FOR EACH ROW
EXECUTE FUNCTION public.fn_valida_misura_controllo_fncsdp();

CREATE TRIGGER trg_touch_fncsdp_subcategory
BEFORE UPDATE
ON public.fncsdp_subcategory
FOR EACH ROW
EXECUTE FUNCTION public.fn_touch_fncsdp();

CREATE TRIGGER trg_touch_controllo_subcategory_fncsdp
BEFORE UPDATE
ON public.controllo_target_subcategory_fncsdp
FOR EACH ROW
EXECUTE FUNCTION public.fn_touch_fncsdp();

DO $$
DECLARE
    v_tabella text;
BEGIN
    FOREACH v_tabella IN ARRAY ARRAY[
        'fncsdp_subcategory',
        'profilo_target_fncsdp',
        'controllo_target_fncsdp',
        'controllo_target_subcategory_fncsdp',
        'assessment_fncsdp',
        'misura_controllo_fncsdp'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I
             BEFORE INSERT OR UPDATE OF attiva, archiviato_il, archiviato_da, motivo_archiviazione
             ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.fn_gestisci_archiviazione_logica()',
            'trg_archiviazione_' || v_tabella,
            v_tabella
        );

        EXECUTE format(
            'CREATE TRIGGER %I
             BEFORE DELETE ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.fn_blocca_cancellazione_fisica()',
            'trg_blocca_delete_' || v_tabella,
            v_tabella
        );
    END LOOP;
END;
$$;

-- =========================================================================
-- 12. AUDIT SPECIALIZZATO FNCSDP
-- =========================================================================

CREATE OR REPLACE FUNCTION public.fn_audit_fncsdp()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
    v_old jsonb;
    v_new jsonb;
    v_riga jsonb;
    v_record_id text;
    v_codice text;
    v_nome text;
    v_utente_id uuid;
    v_utente_email text;
    v_aal text;
    v_ruolo_jwt text;
    v_ruolo_database text;
    v_origine text;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        v_old := to_jsonb(OLD);
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        v_new := to_jsonb(NEW);
    END IF;

    IF TG_OP = 'UPDATE' AND v_old IS NOT DISTINCT FROM v_new THEN
        RETURN NEW;
    END IF;

    v_riga := coalesce(v_new, v_old, '{}'::jsonb);
    v_record_id := coalesce(nullif(v_riga ->> 'id', ''), md5(v_riga::text));
    v_codice := coalesce(nullif(v_riga ->> 'codice', ''), nullif(v_riga ->> 'codice_record', ''));
    v_nome := left(coalesce(nullif(v_riga ->> 'nome', ''), nullif(v_riga ->> 'descrizione', ''), TG_TABLE_NAME), 500);

    v_utente_id := auth.uid();
    v_utente_email := nullif(auth.jwt() ->> 'email', '');
    v_aal := nullif(auth.jwt() ->> 'aal', '');
    v_ruolo_jwt := nullif(auth.jwt() ->> 'role', '');
    v_ruolo_database := session_user;
    v_origine := CASE WHEN v_utente_id IS NOT NULL OR v_utente_email IS NOT NULL THEN 'JWT' ELSE 'DATABASE' END;

    INSERT INTO public.audit_log (
        asset_id,
        utente,
        operazione,
        data_modifica,
        valore_precedente,
        valore_nuovo,
        tabella,
        tipo_entita,
        record_id,
        chiave_record,
        codice_record,
        nome_record,
        servizio_id,
        fornitore_id,
        utente_id,
        utente_email,
        livello_autenticazione,
        ruolo_jwt,
        ruolo_database,
        origine_utente,
        valore_precedente_jsonb,
        valore_nuovo_jsonb
    )
    VALUES (
        NULL,
        coalesce(v_utente_email, v_utente_id::text, v_ruolo_database, 'UTENTE_NON_IDENTIFICATO'),
        TG_OP,
        timezone('UTC', clock_timestamp()),
        CASE WHEN v_old IS NULL THEN NULL ELSE v_old::text END,
        CASE WHEN v_new IS NULL THEN NULL ELSE v_new::text END,
        TG_TABLE_NAME,
        CASE WHEN TG_TABLE_NAME = 'controllo_target_subcategory_fncsdp' THEN 'RELAZIONE' ELSE 'ENTITA' END,
        v_record_id,
        jsonb_strip_nulls(jsonb_build_object(
            'id', v_riga -> 'id',
            'profilo_target_id', v_riga -> 'profilo_target_id',
            'controllo_target_id', v_riga -> 'controllo_target_id',
            'subcategory_id', v_riga -> 'subcategory_id',
            'assessment_id', v_riga -> 'assessment_id'
        )),
        v_codice,
        v_nome,
        NULL,
        NULL,
        v_utente_id,
        v_utente_email,
        v_aal,
        v_ruolo_jwt,
        v_ruolo_database,
        v_origine,
        v_old,
        v_new
    );

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

ALTER FUNCTION public.fn_audit_fncsdp() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.fn_audit_fncsdp() FROM PUBLIC, anon, authenticated;

DO $$
DECLARE
    v_tabella text;
BEGIN
    FOREACH v_tabella IN ARRAY ARRAY[
        'fncsdp_subcategory',
        'profilo_target_fncsdp',
        'controllo_target_fncsdp',
        'controllo_target_subcategory_fncsdp',
        'assessment_fncsdp',
        'misura_controllo_fncsdp'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER %I
             AFTER INSERT OR UPDATE OR DELETE ON public.%I
             FOR EACH ROW
             EXECUTE FUNCTION public.fn_audit_fncsdp()',
            'trg_audit_' || v_tabella,
            v_tabella
        );
    END LOOP;
END;
$$;

-- =========================================================================
-- 13. VISTE APPLICATIVE SECURITY INVOKER
-- =========================================================================

CREATE VIEW public.vista_profili_target_fncsdp
WITH (security_invoker = true)
AS
SELECT
    pt.id AS profilo_target_id,
    pt.organizzazione_id,
    o.codice_organizzazione,
    o.nome AS organizzazione_nome,
    pt.codice,
    pt.nome,
    pt.descrizione,
    pt.perimetro,
    pt.versione,
    pt.stato,
    pt.approvato_il,
    pt.approvato_da,
    pt.attiva,
    pt.creato_il,
    pt.aggiornato_il,
    count(DISTINCT c.id) FILTER (WHERE c.attiva IS TRUE) AS numero_controlli,
    count(DISTINCT m.subcategory_id) FILTER (WHERE m.attiva IS TRUE AND c.attiva IS TRUE) AS numero_subcategory,
    count(DISTINCT a.id) FILTER (WHERE a.attiva IS TRUE) AS numero_assessment,
    max(a.data_assessment) FILTER (WHERE a.attiva IS TRUE) AS ultimo_assessment_il
FROM public.profilo_target_fncsdp pt
JOIN public.organizzazione o ON o.id = pt.organizzazione_id
LEFT JOIN public.controllo_target_fncsdp c ON c.profilo_target_id = pt.id
LEFT JOIN public.controllo_target_subcategory_fncsdp m ON m.controllo_target_id = c.id
LEFT JOIN public.assessment_fncsdp a ON a.profilo_target_id = pt.id
GROUP BY
    pt.id,
    o.codice_organizzazione,
    o.nome;

CREATE VIEW public.vista_controlli_target_fncsdp
WITH (security_invoker = true)
AS
SELECT
    c.id AS controllo_target_id,
    c.profilo_target_id,
    pt.organizzazione_id,
    pt.codice AS profilo_codice,
    pt.nome AS profilo_nome,
    pt.stato AS profilo_stato,
    c.codice,
    c.nome,
    c.descrizione,
    c.copertura_target,
    c.ordine,
    c.attiva,
    s.id AS subcategory_id,
    s.versione_framework,
    s.codice AS subcategory_codice,
    split_part(s.codice, '.', 1) AS funzione_codice,
    split_part(s.codice, '-', 1) AS categoria_codice,
    s.descrizione AS subcategory_descrizione,
    m.peso,
    m.id AS mapping_id
FROM public.controllo_target_fncsdp c
JOIN public.profilo_target_fncsdp pt ON pt.id = c.profilo_target_id
JOIN public.controllo_target_subcategory_fncsdp m
  ON m.controllo_target_id = c.id
 AND m.attiva IS TRUE
JOIN public.fncsdp_subcategory s
  ON s.id = m.subcategory_id
 AND s.attiva IS TRUE;

CREATE VIEW public.vista_profili_attuali_fncsdp
WITH (security_invoker = true)
AS
WITH metriche AS (
    SELECT
        a.id AS assessment_id,
        count(DISTINCT c.id) FILTER (WHERE c.attiva IS TRUE) AS numero_controlli,
        count(DISTINCT mc.id) FILTER (
            WHERE mc.attiva IS TRUE
              AND mc.copertura_attuale IS NOT NULL
        ) AS controlli_misurati,
        count(DISTINCT mc.id) FILTER (
            WHERE mc.attiva IS TRUE
              AND mc.copertura_attuale > 0
              AND mc.livello_maturita IS NOT NULL
        ) AS controlli_con_maturita,
        CASE
            WHEN sum(m.peso) FILTER (WHERE c.attiva IS TRUE AND m.attiva IS TRUE AND c.copertura_target > 0) > 0
            THEN round(
                sum(
                    least(1.00, coalesce(mc.copertura_attuale, 0.00) / nullif(c.copertura_target, 0.00)) * m.peso
                ) FILTER (WHERE c.attiva IS TRUE AND m.attiva IS TRUE AND c.copertura_target > 0)
                /
                sum(m.peso) FILTER (WHERE c.attiva IS TRUE AND m.attiva IS TRUE AND c.copertura_target > 0),
                4
            )
            ELSE NULL
        END AS score,
        CASE
            WHEN sum(m.peso) FILTER (
                WHERE c.attiva IS TRUE
                  AND m.attiva IS TRUE
                  AND mc.copertura_attuale > 0
                  AND mc.livello_maturita IS NOT NULL
            ) > 0
            THEN round(
                sum(mc.livello_maturita * m.peso) FILTER (
                    WHERE c.attiva IS TRUE
                      AND m.attiva IS TRUE
                      AND mc.copertura_attuale > 0
                      AND mc.livello_maturita IS NOT NULL
                )
                /
                sum(m.peso) FILTER (
                    WHERE c.attiva IS TRUE
                      AND m.attiva IS TRUE
                      AND mc.copertura_attuale > 0
                      AND mc.livello_maturita IS NOT NULL
                ),
                2
            )
            ELSE NULL
        END AS maturita_media_indicativa
    FROM public.assessment_fncsdp a
    JOIN public.controllo_target_fncsdp c ON c.profilo_target_id = a.profilo_target_id
    JOIN public.controllo_target_subcategory_fncsdp m ON m.controllo_target_id = c.id
    LEFT JOIN public.misura_controllo_fncsdp mc
      ON mc.assessment_id = a.id
     AND mc.controllo_target_id = c.id
     AND mc.attiva IS TRUE
    GROUP BY a.id
)
SELECT
    a.id AS assessment_id,
    a.profilo_target_id,
    pt.organizzazione_id,
    o.codice_organizzazione,
    o.nome AS organizzazione_nome,
    pt.codice AS profilo_target_codice,
    pt.nome AS profilo_target_nome,
    a.codice,
    a.nome,
    a.data_assessment,
    a.responsabile_assessor_id,
    concat_ws(' ', r.nome, r.cognome) AS assessor_nome,
    r.email AS assessor_email,
    a.note,
    a.stato,
    a.completato_il,
    a.completato_da,
    a.attiva,
    a.creato_il,
    a.aggiornato_il,
    mt.numero_controlli,
    mt.controlli_misurati,
    CASE
        WHEN mt.numero_controlli > 0
        THEN round(mt.controlli_misurati::numeric / mt.numero_controlli::numeric, 4)
        ELSE 0.0000
    END AS avanzamento,
    mt.score,
    CASE WHEN mt.score IS NULL THEN NULL ELSE round(1.0000 - mt.score, 4) END AS gap,
    mt.maturita_media_indicativa
FROM public.assessment_fncsdp a
JOIN public.profilo_target_fncsdp pt ON pt.id = a.profilo_target_id
JOIN public.organizzazione o ON o.id = pt.organizzazione_id
LEFT JOIN public.responsabile r ON r.id = a.responsabile_assessor_id
LEFT JOIN metriche mt ON mt.assessment_id = a.id;

CREATE VIEW public.vista_valutazione_fncsdp
WITH (security_invoker = true)
AS
SELECT
    a.id AS assessment_id,
    a.codice AS assessment_codice,
    a.nome AS assessment_nome,
    a.stato AS assessment_stato,
    a.data_assessment,
    pt.id AS profilo_target_id,
    pt.codice AS profilo_target_codice,
    pt.nome AS profilo_target_nome,
    pt.organizzazione_id,
    o.codice_organizzazione,
    o.nome AS organizzazione_nome,
    c.id AS controllo_target_id,
    c.codice AS controllo_codice,
    c.nome AS controllo_nome,
    c.descrizione AS controllo_descrizione,
    c.copertura_target,
    c.ordine,
    s.id AS subcategory_id,
    s.codice AS subcategory_codice,
    split_part(s.codice, '.', 1) AS funzione_codice,
    split_part(s.codice, '-', 1) AS categoria_codice,
    s.descrizione AS subcategory_descrizione,
    m.peso,
    mc.id AS misura_id,
    mc.risposta,
    mc.note_copertura,
    mc.copertura_attuale,
    mc.note_maturita,
    mc.livello_maturita,
    mc.evidenze,
    mc.note,
    CASE
        WHEN c.copertura_target > 0 AND mc.copertura_attuale IS NOT NULL
        THEN round(least(1.00, mc.copertura_attuale / c.copertura_target), 4)
        ELSE NULL
    END AS rapporto_copertura,
    CASE
        WHEN c.copertura_target > 0 AND mc.copertura_attuale IS NOT NULL
        THEN round(1.00 - least(1.00, mc.copertura_attuale / c.copertura_target), 4)
        ELSE NULL
    END AS gap_controllo,
    CASE
        WHEN c.copertura_target > 0 AND mc.copertura_attuale IS NOT NULL
        THEN round(least(1.00, mc.copertura_attuale / c.copertura_target) * m.peso, 4)
        ELSE NULL
    END AS contributo_pesato
FROM public.assessment_fncsdp a
JOIN public.profilo_target_fncsdp pt ON pt.id = a.profilo_target_id
JOIN public.organizzazione o ON o.id = pt.organizzazione_id
JOIN public.controllo_target_fncsdp c
  ON c.profilo_target_id = pt.id
 AND c.attiva IS TRUE
JOIN public.controllo_target_subcategory_fncsdp m
  ON m.controllo_target_id = c.id
 AND m.attiva IS TRUE
JOIN public.fncsdp_subcategory s
  ON s.id = m.subcategory_id
 AND s.attiva IS TRUE
LEFT JOIN public.misura_controllo_fncsdp mc
  ON mc.assessment_id = a.id
 AND mc.controllo_target_id = c.id
 AND mc.attiva IS TRUE;

-- =========================================================================
-- 14. RLS, POLICY E PRIVILEGI
-- =========================================================================

DO $$
DECLARE
    v_tabella text;
    v_sequenza text;
BEGIN
    FOREACH v_tabella IN ARRAY ARRAY[
        'fncsdp_subcategory',
        'profilo_target_fncsdp',
        'controllo_target_fncsdp',
        'controllo_target_subcategory_fncsdp',
        'assessment_fncsdp',
        'misura_controllo_fncsdp'
    ]
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', v_tabella);
        EXECUTE format('REVOKE ALL PRIVILEGES ON TABLE public.%I FROM anon', v_tabella);
        EXECUTE format('REVOKE DELETE, TRUNCATE ON TABLE public.%I FROM authenticated', v_tabella);
        EXECUTE format('DROP POLICY IF EXISTS "Read_Operativo_Policy" ON public.%I', v_tabella);
        EXECUTE format(
            'CREATE POLICY "Read_Operativo_Policy" ON public.%I
             AS PERMISSIVE FOR SELECT TO authenticated
             USING (public.fn_accesso_operativo())',
            v_tabella
        );

        v_sequenza := pg_get_serial_sequence(format('public.%I', v_tabella), 'id');
        IF v_sequenza IS NOT NULL THEN
            EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', v_sequenza);
            EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM anon', v_sequenza);
        END IF;
    END LOOP;
END;
$$;

GRANT SELECT ON TABLE public.fncsdp_subcategory TO authenticated;

GRANT SELECT, INSERT, UPDATE ON TABLE
    public.profilo_target_fncsdp,
    public.controllo_target_fncsdp,
    public.controllo_target_subcategory_fncsdp,
    public.assessment_fncsdp,
    public.misura_controllo_fncsdp
TO authenticated;

DO $$
DECLARE
    v_tabella text;
BEGIN
    FOREACH v_tabella IN ARRAY ARRAY[
        'profilo_target_fncsdp',
        'controllo_target_fncsdp',
        'controllo_target_subcategory_fncsdp',
        'assessment_fncsdp',
        'misura_controllo_fncsdp'
    ]
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Insert_Operativo_Policy" ON public.%I', v_tabella);
        EXECUTE format('DROP POLICY IF EXISTS "Update_Operativo_Policy" ON public.%I', v_tabella);

        EXECUTE format(
            'CREATE POLICY "Insert_Operativo_Policy" ON public.%I
             AS PERMISSIVE FOR INSERT TO authenticated
             WITH CHECK (public.fn_accesso_operativo())',
            v_tabella
        );

        EXECUTE format(
            'CREATE POLICY "Update_Operativo_Policy" ON public.%I
             AS PERMISSIVE FOR UPDATE TO authenticated
             USING (public.fn_accesso_operativo())
             WITH CHECK (public.fn_accesso_operativo())',
            v_tabella
        );
    END LOOP;
END;
$$;

REVOKE ALL PRIVILEGES ON TABLE
    public.vista_profili_target_fncsdp,
    public.vista_controlli_target_fncsdp,
    public.vista_profili_attuali_fncsdp,
    public.vista_valutazione_fncsdp
FROM anon;

GRANT SELECT ON TABLE
    public.vista_profili_target_fncsdp,
    public.vista_controlli_target_fncsdp,
    public.vista_profili_attuali_fncsdp,
    public.vista_valutazione_fncsdp
TO authenticated;

-- =========================================================================
-- 15. VERIFICHE BLOCCANTI FINALI
-- =========================================================================

DO $$
DECLARE
    v_tabelle integer;
    v_viste integer;
    v_subcategory integer;
    v_rls integer;
    v_security_invoker integer;
    v_trigger_audit integer;
    v_trigger_delete integer;
BEGIN
    SELECT count(*) INTO v_tabelle
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE';

    SELECT count(*) INTO v_viste
    FROM information_schema.views
    WHERE table_schema = 'public';

    SELECT count(*) INTO v_subcategory
    FROM public.fncsdp_subcategory
    WHERE versione_framework = '2.0'
      AND codice IN ('ID.AM-1', 'ID.AM-2', 'ID.AM-3', 'ID.AM-4', 'ID.AM-5', 'ID.AM-6')
      AND attiva IS TRUE;

    SELECT count(*) INTO v_rls
    FROM pg_catalog.pg_class c
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname IN (
          'fncsdp_subcategory',
          'profilo_target_fncsdp',
          'controllo_target_fncsdp',
          'controllo_target_subcategory_fncsdp',
          'assessment_fncsdp',
          'misura_controllo_fncsdp'
      )
      AND c.relrowsecurity IS TRUE;

    SELECT count(*) INTO v_security_invoker
    FROM pg_catalog.pg_class c
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname IN (
          'vista_profili_target_fncsdp',
          'vista_controlli_target_fncsdp',
          'vista_profili_attuali_fncsdp',
          'vista_valutazione_fncsdp'
      )
      AND 'security_invoker=true' = ANY(coalesce(c.reloptions, ARRAY[]::text[]));

    SELECT count(*) INTO v_trigger_audit
    FROM pg_catalog.pg_trigger t
    JOIN pg_catalog.pg_class c ON c.oid = t.tgrelid
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname IN (
          'fncsdp_subcategory',
          'profilo_target_fncsdp',
          'controllo_target_fncsdp',
          'controllo_target_subcategory_fncsdp',
          'assessment_fncsdp',
          'misura_controllo_fncsdp'
      )
      AND t.tgname = 'trg_audit_' || c.relname
      AND NOT t.tgisinternal;

    SELECT count(*) INTO v_trigger_delete
    FROM pg_catalog.pg_trigger t
    JOIN pg_catalog.pg_class c ON c.oid = t.tgrelid
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname IN (
          'fncsdp_subcategory',
          'profilo_target_fncsdp',
          'controllo_target_fncsdp',
          'controllo_target_subcategory_fncsdp',
          'assessment_fncsdp',
          'misura_controllo_fncsdp'
      )
      AND t.tgname = 'trg_blocca_delete_' || c.relname
      AND NOT t.tgisinternal;

    IF v_tabelle <> 36 THEN
        RAISE EXCEPTION 'Conteggio finale tabelle inatteso: % invece di 36.', v_tabelle;
    END IF;

    IF v_viste <> 11 THEN
        RAISE EXCEPTION 'Conteggio finale viste inatteso: % invece di 11.', v_viste;
    END IF;

    IF v_subcategory <> 6 THEN
        RAISE EXCEPTION 'Catalogo ID.AM incompleto: % righe invece di 6.', v_subcategory;
    END IF;

    IF v_rls <> 6 THEN
        RAISE EXCEPTION 'RLS non attiva su tutte le sei tabelle FNCSDP.';
    END IF;

    IF v_security_invoker <> 4 THEN
        RAISE EXCEPTION 'Una o piu viste FNCSDP non sono security_invoker.';
    END IF;

    IF v_trigger_audit <> 6 OR v_trigger_delete <> 6 THEN
        RAISE EXCEPTION 'Trigger FNCSDP incompleti: audit %, blocco DELETE %.', v_trigger_audit, v_trigger_delete;
    END IF;
END;
$$;

COMMIT;

SELECT
    'MIGRAZIONE_30_FNCSDP_COMPLETATA' AS esito,
    36 AS tabelle_attese,
    11 AS viste_attese,
    6 AS subcategory_seed;
